package agent

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/sipeed/picoclaw/pkg/config"
	"github.com/sipeed/picoclaw/pkg/logger"
	"github.com/sipeed/picoclaw/pkg/providers"
	"github.com/sipeed/picoclaw/pkg/routing"
)

// AgentRegistry manages multiple agent instances and routes messages to them.
type AgentRegistry struct {
	agents   map[string]*AgentInstance
	resolver *routing.RouteResolver
	cfg      *config.Config
	provider providers.LLMProvider
	mu       sync.RWMutex
}

// NewAgentRegistry creates a registry from config, instantiating all agents.
func NewAgentRegistry(
	cfg *config.Config,
	provider providers.LLMProvider,
) *AgentRegistry {
	registry := &AgentRegistry{
		agents:   make(map[string]*AgentInstance),
		resolver: routing.NewRouteResolver(cfg),
		cfg:      cfg,
		provider: provider,
	}

	agentConfigs := cfg.Agents.List
	if len(agentConfigs) == 0 {
		implicitAgent := &config.AgentConfig{
			ID:      "main",
			Default: true,
		}
		instance := NewAgentInstance(implicitAgent, &cfg.Agents.Defaults, cfg, provider)
		registry.agents["main"] = instance
		logger.InfoCF("agent", "Created implicit main agent (no agents.list configured)", nil)
	} else {
		for i := range agentConfigs {
			ac := &agentConfigs[i]
			id := routing.NormalizeAgentID(ac.ID)
			instance := NewAgentInstance(ac, &cfg.Agents.Defaults, cfg, provider)
			registry.agents[id] = instance
			logger.InfoCF("agent", "Registered agent",
				map[string]any{
					"agent_id":  id,
					"name":      ac.Name,
					"workspace": instance.Workspace,
					"model":     instance.Model,
				})
		}
	}

	return registry
}

// GetAgent returns the agent instance for a given ID.
// If the agent doesn't exist and auto-registration is enabled, it will create a new agent.
func (r *AgentRegistry) GetAgent(agentID string) (*AgentInstance, bool) {
	id := routing.NormalizeAgentID(agentID)

	// Try to get existing agent first
	r.mu.RLock()
	agent, ok := r.agents[id]
	r.mu.RUnlock()

	if ok {
		return agent, true
	}

	// Check if we should auto-register this agent
	if r.shouldAutoRegister(id) {
		return r.autoRegisterAgent(id)
	}

	return nil, false
}

// ResolveRoute determines which agent handles the message.
func (r *AgentRegistry) ResolveRoute(input routing.RouteInput) routing.ResolvedRoute {
	return r.resolver.ResolveRoute(input)
}

// ListAgentIDs returns all registered agent IDs.
func (r *AgentRegistry) ListAgentIDs() []string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	ids := make([]string, 0, len(r.agents))
	for id := range r.agents {
		ids = append(ids, id)
	}
	return ids
}

// CanSpawnSubagent checks if parentAgentID is allowed to spawn targetAgentID.
func (r *AgentRegistry) CanSpawnSubagent(parentAgentID, targetAgentID string) bool {
	parent, ok := r.GetAgent(parentAgentID)
	if !ok {
		return false
	}
	if parent.Subagents == nil || parent.Subagents.AllowAgents == nil {
		return false
	}
	targetNorm := routing.NormalizeAgentID(targetAgentID)
	for _, allowed := range parent.Subagents.AllowAgents {
		if allowed == "*" {
			return true
		}
		if routing.NormalizeAgentID(allowed) == targetNorm {
			return true
		}
	}
	return false
}

// GetDefaultAgent returns the default agent instance.
func (r *AgentRegistry) GetDefaultAgent() *AgentInstance {
	r.mu.RLock()
	defer r.mu.RUnlock()
	if agent, ok := r.agents["main"]; ok {
		return agent
	}
	for _, agent := range r.agents {
		return agent
	}
	return nil
}

// shouldAutoRegister checks if an agent ID matches the auto-register pattern
func (r *AgentRegistry) shouldAutoRegister(agentID string) bool {
	if r.cfg == nil || !r.cfg.Agents.Defaults.IsAutoRegisterEnabled() {
		return false
	}

	// Only auto-register if the agent ID matches expected pattern format
	// This prevents registering arbitrary agent IDs
	pattern := r.cfg.Agents.Defaults.GetAutoRegisterPattern()

	// Check if agentID could have been generated by the pattern
	// For simplicity, we check if it contains expected separators
	if strings.Contains(pattern, "{channel}") && !strings.Contains(agentID, "-") {
		return false
	}

	return true
}

// autoRegisterAgent creates and registers a new agent dynamically
func (r *AgentRegistry) autoRegisterAgent(agentID string) (*AgentInstance, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()

	// Double-check after acquiring write lock
	if agent, ok := r.agents[agentID]; ok {
		return agent, true
	}

	logger.InfoCF("agent", "Auto-registering new agent",
		map[string]any{
			"agent_id": agentID,
		})

	// Create agent configuration
	agentConfig := &config.AgentConfig{
		ID:        agentID,
		Name:      agentID,
		Workspace: r.buildWorkspacePath(agentID),
	}

	// Initialize tenant workspace
	if err := r.initializeTenantWorkspace(agentConfig.Workspace); err != nil {
		logger.ErrorCF("agent", "Failed to initialize tenant workspace",
			map[string]any{
				"agent_id":  agentID,
				"workspace": agentConfig.Workspace,
				"error":     err.Error(),
			})
		return nil, false
	}

	// Create agent instance
	instance := NewAgentInstance(agentConfig, &r.cfg.Agents.Defaults, r.cfg, r.provider)
	r.agents[agentID] = instance

	logger.InfoCF("agent", "Auto-registered agent successfully",
		map[string]any{
			"agent_id":  agentID,
			"workspace": instance.Workspace,
			"model":     instance.Model,
		})

	return instance, true
}

// buildWorkspacePath constructs the workspace path for an auto-registered agent
func (r *AgentRegistry) buildWorkspacePath(agentID string) string {
	template := r.cfg.Agents.Defaults.GetAutoRegisterWorkspaceTemplate()

	// Replace {agent_id} placeholder
	path := strings.ReplaceAll(template, "{agent_id}", agentID)

	// Expand home directory
	if strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(home, path[2:])
		}
	}

	return path
}

// initializeTenantWorkspace sets up a new tenant workspace with files from default workspace
func (r *AgentRegistry) initializeTenantWorkspace(workspacePath string) error {
	// Create workspace directory if it doesn't exist
	if err := os.MkdirAll(workspacePath, 0755); err != nil {
		return fmt.Errorf("failed to create workspace directory: %w", err)
	}

	autoRegCfg := r.cfg.Agents.Defaults.AutoRegister
	if autoRegCfg == nil || !autoRegCfg.InheritFromDefault {
		return nil
	}

	// Get default workspace path
	defaultWorkspace := r.cfg.Agents.Defaults.Workspace
	if defaultWorkspace == "" {
		// Try to get from default agent
		if defaultAgent := r.GetDefaultAgent(); defaultAgent != nil {
			defaultWorkspace = defaultAgent.Workspace
		}
	}

	if defaultWorkspace == "" {
		logger.WarnCF("agent", "No default workspace found for inheritance", nil)
		return nil
	}

	// Copy specified files
	for _, filename := range autoRegCfg.CopyFiles {
		srcPath := filepath.Join(defaultWorkspace, filename)
		dstPath := filepath.Join(workspacePath, filename)

		if err := r.copyFileIfNotExists(srcPath, dstPath); err != nil {
			logger.WarnCF("agent", "Failed to copy file",
				map[string]any{
					"file":  filename,
					"error": err.Error(),
				})
		}
	}

	// Copy skills directory if enabled
	if autoRegCfg.CopySkills {
		srcSkillsDir := filepath.Join(defaultWorkspace, "skills")
		dstSkillsDir := filepath.Join(workspacePath, "skills")

		if err := r.copyDir(srcSkillsDir, dstSkillsDir); err != nil {
			logger.WarnCF("agent", "Failed to copy skills directory",
				map[string]any{
					"error": err.Error(),
				})
		}
	}

	return nil
}

// copyFileIfNotExists copies a file if the destination doesn't exist
func (r *AgentRegistry) copyFileIfNotExists(src, dst string) error {
	// Check if destination already exists
	if _, err := os.Stat(dst); err == nil {
		return nil // File already exists, skip
	}

	// Check if source exists
	if _, err := os.Stat(src); os.IsNotExist(err) {
		return fmt.Errorf("source file does not exist: %s", src)
	}

	return r.copyFile(src, dst)
}

// copyFile copies a file from src to dst
func (r *AgentRegistry) copyFile(src, dst string) error {
	// Create parent directory if needed
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return fmt.Errorf("failed to create parent directory: %w", err)
	}

	// Open source file
	srcFile, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("failed to open source file: %w", err)
	}
	defer srcFile.Close()

	// Create destination file
	dstFile, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("failed to create destination file: %w", err)
	}
	defer dstFile.Close()

	// Copy content
	if _, err := io.Copy(dstFile, srcFile); err != nil {
		return fmt.Errorf("failed to copy file content: %w", err)
	}

	return nil
}

// copyDir recursively copies a directory
func (r *AgentRegistry) copyDir(src, dst string) error {
	// Check if source directory exists
	srcInfo, err := os.Stat(src)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // Source doesn't exist, skip silently
		}
		return fmt.Errorf("failed to stat source directory: %w", err)
	}

	if !srcInfo.IsDir() {
		return fmt.Errorf("source is not a directory: %s", src)
	}

	// Create destination directory
	if err := os.MkdirAll(dst, srcInfo.Mode()); err != nil {
		return fmt.Errorf("failed to create destination directory: %w", err)
	}

	// Read source directory
	entries, err := os.ReadDir(src)
	if err != nil {
		return fmt.Errorf("failed to read source directory: %w", err)
	}

	// Copy each entry
	for _, entry := range entries {
		srcPath := filepath.Join(src, entry.Name())
		dstPath := filepath.Join(dst, entry.Name())

		if entry.IsDir() {
			// Recursively copy subdirectory
			if err := r.copyDir(srcPath, dstPath); err != nil {
				return err
			}
		} else {
			// Copy file
			if err := r.copyFile(srcPath, dstPath); err != nil {
				return err
			}
		}
	}

	return nil
}
